slam_toolbox:
  ros__parameters:
    # MANDATORY PARAMETERS
    odom_frame: odom
    map_frame: map
    base_frame: ebot_base_link
    scan_topic: /scan

    # --- CRITICAL CHANGES ---

    # 1. Set to 'mapping' to CREATE a new map.
    mode: localization
    use_prior_map: true
    map_file_name: "/root/robows/src/eyrc-25-26/map" # <-- Your saved map
    map_start_pose: [0.0, 0.0, 0.0]
    # 2. Process EVERY scan for maximum detail. (No skipping)
    minimum_travel_distance: 0.001  
    minimum_travel_heading: 0.001

    # 3. Disable the scan matcher. This is the MOST IMPORTANT change.
    # This forces the tool to TRUST your odom 100%.
    ceres_scan_matcher:
      use_scan_matching: false  # <-- THIS IS THE KEY

      # (These weights are now irrelevant but kept for completeness)
      translation_weight: 2.0e2   
      rotation_weight: 4.0e2      
      occupied_space_weight: 5.0
      covariance_scale: 1.0e-4

    # 4. Disable loop closure to prevent map deformation.
    # Setting search distance to 0.0 effectively turns it off.
    loop_search_maximum_distance: 0.0

    # --- Other settings (unchanged, all good) ---
    resolution: 0.04
    map_update_interval: 0.1

    max_laser_range: 7.0
    min_laser_range: 0.3
    #scan_buffer_maximum_scan_distance: 1.0

    optimize_every_n_nodes: 0
    max_laser_range_no_readings: 6.5